---
swagger: "2.0"
info:
  description: "API นี้ใช้งานในเกม PopCat! โดยจะใช้สำหรับการเชื่อมต่อระหว่างเซิร์ฟเวอร์และผู้เล่น"
  version: "1.0.0"
  title: "PopCat!"
  contact:
    email: "perapol_p@cmu.ac.th"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "..."
schemes:
  - "https"
  - "http"

paths:
  /player:
    post:
      summary: "สร้างผู้เล่นใหม่"
      description: "สร้างผู้เล่นใหม่ในเกม PopCat! โดยจะสร้างผู้เล่นใหม่ในเซิร์ฟเวอร์หากชื่อที่ให้มานั้นยังไม่ถูกใช้งาน แต่ถ้าหากชื่อนั้นถูกใช้งานไปแล้วจะได้ผลลัพธ์เป็นข้อมูลผู้ใช้นั้นแทน"
      operationId: "createPlayer"
      consumes:
        - "application/text"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "ชื่อผู้เล่นที่ต้องการสร้าง"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "สร้างผู้เล่นใหม่สำเร็จ หรือ ส่งข้อมูลผู้เล่นที่มีชื่อนั้นอยู่แล้วกลับมา"
          schema:
            $ref: "#/definitions/Player"
          examples:
            application/json:
              name: "popcat"
              clicked: 0
  /player/{name}:
    get:
      summary: "ข้อมูลผู้เล่น"
      description: "ข้อมูลผู้เล่นในเกม PopCat! โดยจะส่งข้อมูลผู้เล่นที่มีชื่อนั้นอยู่แล้วกลับมา"
      operationId: "getPlayer"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "name"
          description: "ชื่อผู้เล่นที่ต้องการข้อมูล"
          required: true
          type: "string"
      responses:
        200:
          description: "ส่งข้อมูลผู้เล่นที่มีชื่อนั้นอยู่แล้วกลับมา"
          schema:
            $ref: "#/definitions/Player"
        404:
          description: "ไม่พบข้อมูลผู้เล่นที่มีชื่อนั้นอยู่"
    put:
      summary: "เพิ่มคลิกให้กับผู้เล่น"
      description: "เพิ่มคลิกให้กับผู้เล่นในเกม PopCat! โดยจะเพิ่มคลิกให้กับผู้เล่นที่มีชื่อนั้นอยู่แล้ว 1 ครั้ง และจะคืนค่าข้อมูลผู้เล่นล่าสุด"
      operationId: "addClick"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "name"
          description: "ชื่อผู้เล่นที่ต้องการเพิ่มคลิก"
          required: true
          type: "string"
      responses:
        200:
          description: "เพิ่มคลิกให้กับผู้เล่นที่มีชื่อนั้นอยู่แล้ว 1 ครั้ง และจะคืนค่าข้อมูลผู้เล่นล่าสุด"
          schema:
            $ref: "#/definitions/Player"
        404:
          description: "ไม่พบข้อมูลผู้เล่นที่มีชื่อนั้นอยู่"
  /player/leaderboard:
    get:
      summary: "อันดับผู้เล่น"
      description: "อันดับผู้เล่นในเกม PopCat! โดยจะส่งข้อมูลผู้เล่นทั้งหมดโดยเรียงลำดับจากจำนวนครั้งที่คลิกมากไปน้อย หากจำนวนครั้งเท่ากันจะเรียงตามชื่อโดยใช้การเรียงลำดับแบบ Natural ordering"
      operationId: "getLeaderboard"
      produces:
        - "application/json"
      responses:
        200:
          description: "ส่งข้อมูลผู้เล่นทั้งหมดโดยเรียงลำดับจากจำนวนครั้งที่คลิกมากไปน้อย หากจำนวนครั้งเท่ากันจะเรียงตามชื่อโดยใช้การเรียงลำดับแบบ Natural ordering"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Player"
            example:
              - name: "popcat"
                clicked: 100
              - name: "popcat2"
                clicked: 99
              - name: "popcat3"
                clicked: 99
              - name: "popcat4"
                clicked: 98

definitions:
  Player:
    type: "object"
    properties:
      name:
        type: "string"
        description: "ชื่อของผู้เล่น"
      clicked:
        type: "integer"
        description: "จำนวนครั้งที่ผู้เล่นคลิก"
    example:
      name: "popcat"
      clicked: 100